### ISSUE TITLE
Update Riff Raff configuration

### ISSUE THREAD

**Issue by DavidLawes** [guardian/mobile-save-for-later#82]
The master branch of this repository has been migrated to main using the [master-to-main](https://github.com/guardian/master-to-main) tool.

  The following `riff-raff.yaml` file(s) have been found in the repostiory:

  - [ ] [mobile-save-for-later/riff-raff.yaml](https://github.com/guardian/mobile-save-for-later/blob/main/mobile-save-for-later/riff-raff.yaml)
- [ ] [mobile-save-for-later-user-deletion/riff-raff.yaml](https://github.com/guardian/mobile-save-for-later/blob/main/mobile-save-for-later-user-deletion/riff-raff.yaml)

For each deployment, you will need to complete the following steps:

1. Fix continuous deployments: https://riffraff.gutools.co.uk/deployment/continuous
1. Ensure blocked deployments are still blocked: https://riffraff.gutools.co.uk/deployment/restrictions

**Comment by mbd0910** [comment]
RiffRaff updated to point at Github Actions instead of Team City. Verified working as expected after merging https://github.com/guardian/mobile-save-for-later/pull/93
