### ISSUE TITLE
Check references to master

### ISSUE THREAD

**Issue by DavidLawes** [guardian/mobile-save-for-later#83]
The master branch of this repository has been migrated to main using the [master-to-main](https://github.com/guardian/master-to-main) tool.

  Some files in the repository contain the word master. Please check the following files and update where required:

  - [x] [.github/workflows/snyk.yml](https://github.com/guardian/mobile-save-for-later/blob/main/.github/workflows/snyk.yml)
- [x] [README.md](https://github.com/guardian/mobile-save-for-later/blob/main/README.md)
- [x] [common/src/main/scala/com/gu/sfl/model/model.scala](https://github.com/guardian/mobile-save-for-later/blob/main/common/src/main/scala/com/gu/sfl/model/model.scala)

**Comment by DavidLawes** [comment]
- updated snyk
- readme references external repo that does not exist on `main` branch
- the note model.scala has the same issue as the readme (external repo doesn't exist on `main` branch)

**Comment by mbd0910** [comment]
https://github.com/guardian/mobile-save-for-later/pull/91
https://github.com/guardian/mobile-save-for-later/pull/93
